/* =====================================================================
   DevBank - Script de setup do ambiente
   ---------------------------------------------------------------------
   Cria o schema da fintech ficticia "DevBank" e carrega dados de teste.

   - Pode ser executado quantas vezes quiser: apaga e recria as TABELAS.
     As functions/procedures que voce criou NAO sao apagadas (elas ficam
     INVALID por um instante e recompilam sozinhas no proximo uso).
   - Compativel com Oracle 12c ou superior (19c, 21c, Oracle Database Free,
     FreeSQL).
   - No SQL Developer, rode com F5 ("Executar Script"), nao com Ctrl+Enter.
   - Os dados nao tem acentos de proposito, para evitar problema de
     encoding em alguns clientes SQL.
   ===================================================================== */

-- ---------------------------------------------------------------------
-- 0. Limpeza (permite rodar o script de novo para "resetar" os dados)
-- ---------------------------------------------------------------------
BEGIN
  FOR t IN (SELECT table_name
              FROM user_tables
             WHERE table_name IN ('LOG_AUDITORIA', 'TRANSACOES', 'CHAVES_PIX',
                                  'CONTAS', 'CLIENTES')) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

-- ---------------------------------------------------------------------
-- 1. Tabelas
-- ---------------------------------------------------------------------
CREATE TABLE clientes (
  id_cliente      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100)
                  CONSTRAINT pk_clientes PRIMARY KEY,
  nome            VARCHAR2(100) NOT NULL,
  cpf             VARCHAR2(11)  NOT NULL CONSTRAINT uk_clientes_cpf UNIQUE,  -- so digitos
  email           VARCHAR2(100) NOT NULL,
  telefone        VARCHAR2(20),
  data_nascimento DATE          NOT NULL,
  renda_mensal    NUMBER(12,2)  NOT NULL,
  score_credito   NUMBER(4)     NOT NULL
                  CONSTRAINT ck_clientes_score CHECK (score_credito BETWEEN 0 AND 1000),
  status          VARCHAR2(10)  DEFAULT 'ATIVO' NOT NULL
                  CONSTRAINT ck_clientes_status CHECK (status IN ('ATIVO', 'INATIVO')),
  data_cadastro   DATE          DEFAULT SYSDATE NOT NULL
);

CREATE TABLE contas (
  id_conta          NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 2000)
                    CONSTRAINT pk_contas PRIMARY KEY,
  id_cliente        NUMBER NOT NULL
                    CONSTRAINT fk_contas_cliente REFERENCES clientes (id_cliente),
  tipo              VARCHAR2(10) NOT NULL
                    CONSTRAINT ck_contas_tipo CHECK (tipo IN ('CORRENTE', 'POUPANCA')),
  saldo             NUMBER(15,2) DEFAULT 0 NOT NULL
                    CONSTRAINT ck_contas_saldo CHECK (saldo >= 0),   -- defesa em profundidade
  limite_pix_diario NUMBER(15,2) DEFAULT 1000 NOT NULL,
  status            VARCHAR2(10) DEFAULT 'ATIVA' NOT NULL
                    CONSTRAINT ck_contas_status CHECK (status IN ('ATIVA', 'BLOQUEADA', 'ENCERRADA')),
  data_abertura     DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE chaves_pix (
  chave        VARCHAR2(100) CONSTRAINT pk_chaves_pix PRIMARY KEY,
  tipo_chave   VARCHAR2(10)  NOT NULL
               CONSTRAINT ck_chaves_tipo CHECK (tipo_chave IN ('CPF', 'EMAIL', 'TELEFONE', 'ALEATORIA')),
  id_conta     NUMBER NOT NULL
               CONSTRAINT fk_chaves_conta REFERENCES contas (id_conta),
  data_criacao DATE DEFAULT SYSDATE NOT NULL
);

-- DEPOSITO: so conta destino | SAQUE/TARIFA: so conta origem | PIX: as duas
CREATE TABLE transacoes (
  id_transacao     NUMBER GENERATED BY DEFAULT AS IDENTITY
                   CONSTRAINT pk_transacoes PRIMARY KEY,
  id_conta_origem  NUMBER CONSTRAINT fk_transacoes_origem  REFERENCES contas (id_conta),
  id_conta_destino NUMBER CONSTRAINT fk_transacoes_destino REFERENCES contas (id_conta),
  tipo             VARCHAR2(10) NOT NULL
                   CONSTRAINT ck_transacoes_tipo CHECK (tipo IN ('PIX', 'DEPOSITO', 'SAQUE', 'TARIFA')),
  valor            NUMBER(15,2) NOT NULL
                   CONSTRAINT ck_transacoes_valor CHECK (valor > 0),
  status           VARCHAR2(10) DEFAULT 'CONCLUIDA' NOT NULL
                   CONSTRAINT ck_transacoes_status CHECK (status IN ('CONCLUIDA', 'RECUSADA')),
  motivo_recusa    VARCHAR2(200),
  data_hora        DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE log_auditoria (
  id_log    NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_log_auditoria PRIMARY KEY,
  nivel     VARCHAR2(10)   NOT NULL,          -- INFO / ERRO
  origem    VARCHAR2(60)   NOT NULL,          -- nome da rotina que gerou o log
  mensagem  VARCHAR2(4000),
  usuario   VARCHAR2(128)  DEFAULT USER NOT NULL,
  data_hora DATE           DEFAULT SYSDATE NOT NULL
);

-- Indices que as rotinas do dia a dia vao usar
CREATE INDEX ix_contas_cliente         ON contas (id_cliente);
CREATE INDEX ix_chaves_pix_conta       ON chaves_pix (id_conta);
CREATE INDEX ix_transacoes_origem_data ON transacoes (id_conta_origem, data_hora);

-- ---------------------------------------------------------------------
-- 2. Dados de teste
--    Cada cliente foi escolhido para testar uma regra (veja comentarios).
-- ---------------------------------------------------------------------
INSERT INTO clientes (id_cliente, nome, cpf, email, telefone, data_nascimento, renda_mensal, score_credito, status, data_cadastro)
VALUES (1, 'Ana Souza', '15881399803', 'ana.souza@email.com', '+5511911112222', DATE '1988-03-14', 15000.00, 850, 'ATIVO', DATE '2019-02-10');       -- OURO

INSERT INTO clientes (id_cliente, nome, cpf, email, telefone, data_nascimento, renda_mensal, score_credito, status, data_cadastro)
VALUES (2, 'Bruno Lima', '69879730917', 'bruno.lima@email.com', '+5511922223333', DATE '1995-07-22', 4500.00, 620, 'ATIVO', DATE '2021-06-15');     -- PRATA

INSERT INTO clientes (id_cliente, nome, cpf, email, telefone, data_nascimento, renda_mensal, score_credito, status, data_cadastro)
VALUES (3, 'Carla Mendes', '11417075350', 'carla.mendes@email.com', '+5511988887777', DATE '2003-11-05', 2200.00, 710, 'ATIVO', DATE '2023-01-20'); -- BRONZE

INSERT INTO clientes (id_cliente, nome, cpf, email, telefone, data_nascimento, renda_mensal, score_credito, status, data_cadastro)
VALUES (4, 'Diego Rocha', '64556815177', 'diego.rocha@email.com', '+5531933334444', DATE '1979-01-30', 12000.00, 250, 'ATIVO', DATE '2020-10-05');  -- RISCO (rico, mas score baixo)

INSERT INTO clientes (id_cliente, nome, cpf, email, telefone, data_nascimento, renda_mensal, score_credito, status, data_cadastro)
VALUES (5, 'Eduarda Alves', '88447294072', 'eduarda.alves@email.com', '+5541944445555', DATE '2000-09-18', 3000.00, 500, 'ATIVO', DATE '2022-04-11'); -- PRATA (no limite exato)

INSERT INTO clientes (id_cliente, nome, cpf, email, telefone, data_nascimento, renda_mensal, score_credito, status, data_cadastro)
VALUES (6, 'Felipe Costa', '55761698757', 'felipe.costa@email.com', '+5551955556666', DATE '1992-12-01', 9999.99, 900, 'ATIVO', DATE '2021-09-30');  -- PRATA (1 centavo abaixo de OURO)

INSERT INTO clientes (id_cliente, nome, cpf, email, telefone, data_nascimento, renda_mensal, score_credito, status, data_cadastro)
VALUES (7, 'Gabriela Nunes', '16897684600', 'gabriela.nunes@email.com', '+5561966667777', DATE '1985-06-25', 10000.00, 700, 'ATIVO', DATE '2018-12-03'); -- OURO (no limite exato)

INSERT INTO clientes (id_cliente, nome, cpf, email, telefone, data_nascimento, renda_mensal, score_credito, status, data_cadastro)
VALUES (8, 'Henrique Dias', '97880932055', 'henrique.dias@email.com', '+5521977776666', DATE '2005-04-09', 1800.00, 300, 'ATIVO', DATE '2024-02-14'); -- BRONZE | CPF INVALIDO (legado)

INSERT INTO clientes (id_cliente, nome, cpf, email, telefone, data_nascimento, renda_mensal, score_credito, status, data_cadastro)
VALUES (9, 'Isabela Ramos', '81967273138', 'isabela.ramos@email.com', '+5571988889999', DATE '1998-08-12', 6000.00, 450, 'ATIVO', DATE '2022-07-07');  -- BRONZE

INSERT INTO clientes (id_cliente, nome, cpf, email, telefone, data_nascimento, renda_mensal, score_credito, status, data_cadastro)
VALUES (10, 'Joao Pereira', '11111111111', 'joao.pereira@email.com', '+5511999990000', DATE '1970-02-17', 25000.00, 950, 'INATIVO', DATE '2015-05-05'); -- INATIVO | CPF INVALIDO (legado)

-- Contas: 1001..1012 (contas novas criadas pelas procedures comecam em 2000)
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1001, 1,  'CORRENTE', 25000.00, 5000,  'ATIVA',     DATE '2019-02-10');
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1002, 1,  'POUPANCA', 80000.00, 1000,  'ATIVA',     DATE '2019-03-01');
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1003, 2,  'CORRENTE',  3200.50, 2000,  'ATIVA',     DATE '2021-06-15');
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1004, 3,  'CORRENTE',   450.00, 1000,  'ATIVA',     DATE '2023-01-20');
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1005, 4,  'CORRENTE', 12000.00, 3000,  'ATIVA',     DATE '2020-10-05');
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1006, 5,  'CORRENTE',  1500.00, 1000,  'ATIVA',     DATE '2022-04-11');
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1007, 6,  'CORRENTE',  7800.00, 3000,  'ATIVA',     DATE '2021-09-30');
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1008, 7,  'CORRENTE', 18500.00, 5000,  'ATIVA',     DATE '2018-12-03');
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1009, 8,  'CORRENTE',     5.00,  500,  'ATIVA',     DATE '2024-02-14'); -- quase sem saldo
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1010, 9,  'CORRENTE',  2300.00, 1000,  'BLOQUEADA', DATE '2022-07-07');
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1011, 10, 'CORRENTE',     0.00, 10000, 'ENCERRADA', DATE '2015-05-05');
INSERT INTO contas (id_conta, id_cliente, tipo, saldo, limite_pix_diario, status, data_abertura) VALUES (1012, 9,  'POUPANCA',   900.00, 1000,  'ATIVA',     DATE '2023-03-03');

-- Chaves Pix
INSERT INTO chaves_pix (chave, tipo_chave, id_conta) VALUES ('15881399803',                          'CPF',       1001);
INSERT INTO chaves_pix (chave, tipo_chave, id_conta) VALUES ('ana.souza@email.com',                  'EMAIL',     1002);
INSERT INTO chaves_pix (chave, tipo_chave, id_conta) VALUES ('bruno.lima@email.com',                 'EMAIL',     1003);
INSERT INTO chaves_pix (chave, tipo_chave, id_conta) VALUES ('+5511988887777',                       'TELEFONE',  1004);
INSERT INTO chaves_pix (chave, tipo_chave, id_conta) VALUES ('64556815177',                          'CPF',       1005);
INSERT INTO chaves_pix (chave, tipo_chave, id_conta) VALUES ('eduarda.alves@email.com',              'EMAIL',     1006);
INSERT INTO chaves_pix (chave, tipo_chave, id_conta) VALUES ('f47ac10b-58cc-4372-a567-0e02b2c3d479', 'ALEATORIA', 1007);
INSERT INTO chaves_pix (chave, tipo_chave, id_conta) VALUES ('gabriela.nunes@email.com',             'EMAIL',     1008);
INSERT INTO chaves_pix (chave, tipo_chave, id_conta) VALUES ('+5521977776666',                       'TELEFONE',  1009);
INSERT INTO chaves_pix (chave, tipo_chave, id_conta) VALUES ('isabela.ramos@email.com',              'EMAIL',     1010); -- conta BLOQUEADA
INSERT INTO chaves_pix (chave, tipo_chave, id_conta) VALUES ('joao.pereira@email.com',               'EMAIL',     1011); -- conta ENCERRADA

-- Historico de transacoes
-- Depositos e movimentacoes dos ultimos 30 dias
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (NULL, 1001, 'DEPOSITO', 5000.00, SYSDATE - 30);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (NULL, 1003, 'DEPOSITO', 3500.00, SYSDATE - 28);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (NULL, 1004, 'DEPOSITO', 1200.00, SYSDATE - 25);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (NULL, 1008, 'DEPOSITO', 8000.00, SYSDATE - 20);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (NULL, 1006, 'DEPOSITO', 2000.00, SYSDATE - 15);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (1001, 1003, 'PIX',       250.00, SYSDATE - 12);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (1008, 1004, 'PIX',       300.00, SYSDATE - 10);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (1007, 1006, 'PIX',       120.75, SYSDATE - 7);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (1004, NULL, 'SAQUE',     200.00, SYSDATE - 5);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (1003, 1007, 'PIX',        89.90, SYSDATE - 3);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (1005, 1004, 'PIX',        50.00, SYSDATE - 2);

-- Bruno (conta 1003, limite diario R$ 2.000): Pix de ONTEM nao conta no limite de hoje
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora)
VALUES (1003, 1002, 'PIX', 1000.00, TRUNC(SYSDATE) - 1 + 10/24);

-- Bruno HOJE: ja enviou R$ 1.500 (1000 + 500) e teve 1 Pix RECUSADO (que nao conta)
-- TRUNC(SYSDATE) + (SYSDATE - TRUNC(SYSDATE)) * fracao = sempre "hoje, antes de agora"
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora)
VALUES (1003, 1004, 'PIX', 1000.00, TRUNC(SYSDATE) + (SYSDATE - TRUNC(SYSDATE)) / 4);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora)
VALUES (1003, 1008, 'PIX',  500.00, TRUNC(SYSDATE) + (SYSDATE - TRUNC(SYSDATE)) / 3);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, status, motivo_recusa, data_hora)
VALUES (1003, 1006, 'PIX',  800.00, 'RECUSADA', 'Limite diario de Pix excedido', TRUNC(SYSDATE) + (SYSDATE - TRUNC(SYSDATE)) / 2);

-- Diego (conta 1005, cliente RISCO): rajada de 5 Pix nos ultimos 40 minutos (caso para o antifraude)
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (1005, 1004, 'PIX', 199.90, SYSDATE - 40/1440);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (1005, 1006, 'PIX', 199.90, SYSDATE - 32/1440);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (1005, 1009, 'PIX', 199.90, SYSDATE - 25/1440);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (1005, 1004, 'PIX', 199.90, SYSDATE - 12/1440);
INSERT INTO transacoes (id_conta_origem, id_conta_destino, tipo, valor, data_hora) VALUES (1005, 1006, 'PIX', 199.90, SYSDATE -  5/1440);

COMMIT;

-- ---------------------------------------------------------------------
-- 3. Codigo "legado" da empresa que voce vai reutilizar
--    Grava log de auditoria em uma TRANSACAO AUTONOMA: o log fica gravado
--    mesmo que a rotina que chamou faca ROLLBACK depois.
-- ---------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE sp_log (
  p_nivel    IN VARCHAR2,
  p_origem   IN VARCHAR2,
  p_mensagem IN VARCHAR2
) IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO log_auditoria (nivel, origem, mensagem)
  VALUES (p_nivel, p_origem, SUBSTR(p_mensagem, 1, 4000));
  COMMIT;
END sp_log;
/

-- ---------------------------------------------------------------------
-- 4. Conferencia
-- ---------------------------------------------------------------------
SELECT 'clientes'   AS tabela, COUNT(*) AS linhas FROM clientes   UNION ALL
SELECT 'contas',               COUNT(*)           FROM contas     UNION ALL
SELECT 'chaves_pix',           COUNT(*)           FROM chaves_pix UNION ALL
SELECT 'transacoes',           COUNT(*)           FROM transacoes;
-- Esperado: clientes 10 | contas 12 | chaves_pix 11 | transacoes 20
